# Generated by Django 4.1 on 2022-08-29 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_message_options_message_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='profile',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mreceiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msender', to=settings.AUTH_USER_MODEL),
        ),
    ]
